FROM node:alpine

WORKDIR /usr/src/app
COPY ./package.json ./
COPY ./pnpm-lock.yaml ./

RUN npm i -g pnpm
RUN pnpm install

COPY ./src ./src

COPY ./db.env ./
COPY ./express.env ./

COPY tsconfig.json ./

CMD ["pnpm", "dev"]